# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import datetime

### Step 2. Import the dataset from this [address](https://github.com/guipsamora/pandas_exercises/blob/master/Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [3]:
data = pd.read_csv('c:/Github/pandas_exercises/06_Stats/Wind_Stats/wind.data', sep='\s+',  parse_dates = [[0, 1, 2]]) 
#parse_dates将前3列解析成日期

In [4]:
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.
创建清洗日期列的函数：将20xx年替换成19xx年

In [25]:
def fix_year(date):
    return date if date.year <= 2000 else datetime.date(date.year-100, date.month, date.day)

In [27]:
data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_year)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [29]:
data = data.set_index('Yr_Mo_Dy')

In [31]:
data.index

DatetimeIndex(['1961-01-01', '1961-01-02', '1961-01-03', '1961-01-04',
               '1961-01-05', '1961-01-06', '1961-01-07', '1961-01-08',
               '1961-01-09', '1961-01-10',
               ...
               '1978-12-22', '1978-12-23', '1978-12-24', '1978-12-25',
               '1978-12-26', '1978-12-27', '1978-12-28', '1978-12-29',
               '1978-12-30', '1978-12-31'],
              dtype='datetime64[ns]', name='Yr_Mo_Dy', length=6574, freq=None)

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below. 
计算每列的空值数目

In [33]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.
计算每列的非空元素数据

In [68]:
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.
计算所有时期所有类型的平均风速

In [69]:
data.mean().mean()

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.
对每列算所有日期范围内的最小值、最大值、均值和标准差

In [47]:
loc_stats = data.agg([min, max, np.mean, np.std])

In [70]:
loc_stats.head().T

      min    max       mean       std
RPT  0.67  35.80  12.362987  5.618413
VAL  0.21  33.37  10.644314  5.267356
ROS  1.50  33.84  11.660526  5.008450
KIL  0.00  28.46   6.306468  3.605811
SHA  0.13  37.54  10.455834  4.936125
BIR  0.00  26.16   7.092254  3.968683
DUB  0.00  30.37   9.797343  4.977555
CLA  0.00  31.08   8.495053  4.499449
MUL  0.00  25.88   8.493590  4.166872
CLO  0.04  28.21   8.707332  4.503954
BEL  0.13  42.38  13.121007  5.835037
MAL  0.67  42.54  15.599079  6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.
对每行求所有飓风类型范围的最小值、最大值、均值和标准差

In [49]:
day_stats = data.agg([min, max, np.mean, np.std], axis=1)

In [50]:
day_stats.head()

             min    max       mean       std
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.
计算一月的风速均值,不同年份的一月份都视为一月份

In [54]:
data[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.
计算每列按年聚合的均值

In [55]:
data.resample('AS').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-01-01,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-01-01,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-01-01,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-01-01,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-01-01,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-01-01,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-01-01,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-01-01,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-01-01,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-01-01,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-01-01,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-01-01,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-01-01,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-01-01,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-01-01,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-01-01,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-01-01,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.
计算每列按月聚合的平均值

In [56]:
data.resample('MS').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02-01,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03-01,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04-01,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05-01,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08-01,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09-01,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10-01,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11-01,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12-01,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.
按周聚合

In [58]:
data.resample('W').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

### Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [67]:
data.loc['1961/1/2':, :].resample('W-Mon').mean()[:52]

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-02,14.710000,NaN,10.830000,6.500000,12.620000,7.670000,11.500000,10.040000,9.790000,9.670000,17.540000,13.830000
1961-01-09,13.237143,11.392857,10.368571,6.167143,9.152857,6.310000,10.567143,6.631667,8.148571,8.412857,11.838571,13.458571
1961-01-16,13.017143,9.027143,12.768571,4.624286,7.490000,5.091429,7.708571,6.628571,5.772857,7.321429,11.125714,10.120000
1961-01-23,13.221429,9.678571,13.392857,7.150000,9.326667,8.238571,9.892857,8.584286,7.508571,8.958571,10.071429,13.082857
1961-01-30,19.158333,16.350000,17.137143,12.357143,17.372857,14.392857,15.642857,14.654286,14.361429,15.467143,21.514286,22.340000
1961-02-06,18.582857,16.792857,14.004286,9.311429,15.111429,10.250000,12.871429,9.774286,11.112857,9.817143,15.084286,12.305714
1961-02-13,19.398571,16.267143,17.131429,10.770000,13.404286,12.094286,14.492857,14.182857,13.350000,14.742857,22.152857,18.845714
1961-02-20,13.492857,13.860000,12.542857,8.915000,12.665714,10.964286,8.281429,11.218571,11.642857,12.757143,19.234286,15.512857
1961-02-27,15.215714,13.952857,14.411429,8.315714,13.982857,10.180000,11.935714,11.315714,10.685714,12.957143,17.005714,15.090000
1961-03-06,11.227143,12.195714,10.458333,7.300000,10.987143,8.571429,8.815714,10.338571,9.438333,11.287143,16.444286,11.951667
1961-03-13,10.431667,12.044286,11.530000,7.494286,11.762857,10.417143,8.471429,10.381429,11.124286,11.374286,18.057143,16.325714
1961-03-20,12.274286,13.368571,11.560000,7.815714,10.792857,8.611429,10.248571,10.154286,10.071429,11.960000,18.577143,16.542857
1961-03-27,8.442857,7.400000,8.720000,5.505714,7.731429,7.012857,9.537143,7.751429,9.880000,10.522857,13.025714,17.312857
1961-04-03,12.101429,9.585714,11.001429,7.528333,11.035714,9.957143,10.947143,10.072857,10.658333,9.322857,14.024286,13.048571
1961-04-10,10.601429,10.111429,12.547143,5.798571,8.870000,6.952857,7.065714,7.332857,7.935714,7.184286,11.218571,11.638571
1961-04-17,8.715714,7.840000,8.084286,4.768571,5.881429,4.458571,4.898571,4.845714,5.372857,6.071429,9.828571,8.118571
1961-04-24,13.412857,11.057143,11.084286,8.227143,11.118571,8.501429,9.112857,9.760000,9.112857,10.092857,13.595714,12.642857
1961-05-01,11.021429,10.632857,9.172857,5.515714,8.738571,5.828571,6.822857,7.371429,6.778571,6.452857,10.971429,9.017143
1961-05-08,14.927143,13.427143,13.400000,10.090000,15.238571,11.417143,12.667143,12.494286,12.760000,12.728571,17.552857,16.740000
1961-05-15,7.320000,7.832857,7.804286,4.314286,7.710000,4.880000,5.901667,5.637143,5.964286,6.155714,8.702857,7.828571
1961-05-22,7.744286,5.590000,11.411429,4.061429,7.388571,5.070000,5.197143,6.731429,6.597143,6.988571,9.850000,10.970000
1961-05-29,8.982857,7.817143,10.031429,4.976667,7.494286,4.780000,6.470000,6.987143,7.042857,8.488571,10.994286,12.702857
1961-06-05,10.255714,8.102857,8.857143,5.708571,10.028571,6.105714,7.160000,8.630000,8.272857,8.875714,12.960000,12.787143
1961-06-12,10.584286,8.355714,8.947143,5.144286,9.415714,5.115714,7.905714,5.985714,7.808571,7.812857,8.880000,12.114286
1961-06-19,10.524286,9.465714,10.048571,6.698571,11.071429,7.535714,9.450000,10.031429,9.534286,10.071429,16.155714,15.817143
1961-06-26,7.947143,6.828571,8.077143,5.572857,11.631429,7.237143,11.584286,9.214286,10.370000,11.238571,14.071429,16.660000
1961-07-03,10.605000,9.362857,9.298571,7.201429,11.855714,7.281429,8.695714,10.177143,8.731429,11.232857,15.904286,13.743333
1961-07-10,10.757143,6.832857,8.914286,6.901429,11.191429,6.851429,9.708333,7.684286,8.941429,8.755714,10.024286,13.797143
1961-07-17,16.054286,12.834286,10.618571,8.688571,13.892857,8.198571,10.801429,10.828571,9.921429,10.638571,13.681429,12.977143
1961-07-24,4.595714,4.477143,6.875714,3.495714,6.101429,2.852857,3.464286,5.494286,4.804286,5.655714,7.964286,7.987143
1961-07-31,10.657143,8.742857,9.775714,5.918571,10.118571,6.534286,9.171429,8.924286,8.174286,9.558571,12.401429,14.267143
1961-08-07,10.185714,8.465714,9.424286,6.077143,11.351429,7.351429,8.690000,8.664286,8.011429,8.975714,12.118571,13.218571
1961-08-14,12.315000,8.864286,9.232857,5.900000,11.481429,7.088571,9.460000,9.211429,7.671429,8.436667,11.725714,10.833333
1961-08-21,15.855714,11.094286,11.744286,9.011429,15.952857,10.970000,13.774286,12.345714,12.441429,12.607143,15.614286,17.435714
1961-08-28,11.707143,12.490000,12.501429,7.215714,12.761429,9.101429,9.688571,11.742857,9.245714,12.144286,16.328571,15.700000
1961-09-04,7.738571,6.112857,5.608571,4.321429,7.840000,4.720000,5.315714,6.845714,5.238571,7.328571,11.472857,9.105714
1961-09-11,10.981429,9.567143,8.542857,6.387143,10.284286,6.507143,7.841429,7.608571,7.804286,8.697143,11.915714,12.648571
1961-09-18,17.142857,13.838571,17.005000,11.273333,14.551429,10.588571,11.630000,13.861667,10.770000,13.774286,18.920000,18.204286
1961-09-25,8.584286,8.398571,8.118571,4.985714,9.041429,5.548571,6.350000,7.684286,5.564286,7.768571,12.870000,10.814286
1961-10-02,16.580000,10.653333,13.730000,8.762857,13.434286,8.965714,9.197143,9.937143,9.248571,11.714286,14.410000,13.825714
1961-10-09,11.682857,9.334286,11.227143,5.382857,8.392857,5.385714,7.458571,6.244286,5.204286,7.390000,8.947143,10.440000
1961-10-16,10.125000,9.728571,7.527143,6.554286,11.351429,8.132857,9.500000,8.365714,7.958571,9.881429,16.028571,16.944286
1961-10-23,20.212857,13.755714,16.638571,12.845714,15.428571,11.114286,15.798571,12.678571,13.338571,17.151429,17.864286,23.695714
1961-10-30,14.672857,10.910000,13.881429,7.778571,12.500000,8.434286,12.561429,9.492857,8.928333,12.120000,14.872857,17.778571
1961-11-06,11.362857,9.178571,10.017143,7.064286,10.310000,8.095714,11.838571,9.405714,9.458571,11.321429,15.655714,18.178571
1961-11-13,11.434286,8.714286,14.255714,6.130000,7.577143,4.994286,11.260000,4.744286,5.801429,7.261429,8.732857,10.822857
1961-11-20,10.202857,6.564286,14.381429,4.708571,7.898571,4.718571,8.398571,4.287143,3.948571,5.150000,5.655714,5.088571
1961-11-27,8.738571,7.534286,8.108571,5.000000,8.362857,6.015714,10.901667,6.102857,5.952857,8.977143,11.457143,12.328571
1961-12-04,14.738571,12.204286,12.797143,7.310000,11.695714,8.362857,12.214286,8.155714,8.455714,9.464286,13.791429,16.630000
1961-12-11,17.150000,14.274286,15.347143,9.088571,13.565714,10.718571,16.235714,10.001429,11.030000,12.438571,16.124286,16.117143
1961-12-18,13.675714,12.794286,12.160000,7.007143,12.684286,10.527143,10.690000,8.911429,8.732857,9.125714,12.684286,12.868571
1961-12-25,16.815714,11.780000,14.305714,6.458571,12.304286,7.297143,9.090000,8.161429,6.457143,8.505714,11.012857,9.265714